version: '3.1'
services:
  mysql:
    image: 'mysql:latest'
    ports:
      - 3306:3306

    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_pw
      MYSQL_DATABASE_FILE: /run/secrets/mysql_database

    secrets:
      - mysql_root_pw
      - mysql_database

secrets:
  mysql_root_pw:
    file: ./docker-secrets/mysql_root_pw
  mysql_database:
    file: ./docker-secrets/mysql_database